Acme\FeedbackBundle\Entity\Feedback:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    userId:
      type: integer
      length: '11'
    description:
      type: text
      length: null
  lifecycleCallbacks: {  }
