<?php

namespace Acme\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends EntityRepository
{
	public function findOneByCalendarName($name,$user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM AcmeTaskBundle:Calendar c WHERE c.title = \''.$name.'\' AND c.ownerId	= '.$user->getId().' ')
            ->getSingleResult();
    }
    public function findByUser($user) {
    	$cals = $this->getEntityManager()
            ->createQuery('SELECT c FROM AcmeTaskBundle:Calendar c WHERE c.ownerId	= '.$user->getId().' ')
            ->getResult();
      $calendars = array( 0 => 'User' );
    	foreach($cals as $cal){
    		$calendars[$cal->getId()] = $cal->getTitle();
    	}
    	return $calendars;
    }
    public function findByOwnerIdandEnabled($user) {
    	return $this->getEntityManager()
            ->createQuery('SELECT c FROM AcmeTaskBundle:Calendar c WHERE c.ownerId = '.$user->getId().' AND c.enabled = 1 ')
            ->getResult();
    }
}