<?php

namespace Acme\TaskBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
	public function findByPendingNotifications() {
		$now = mktime(date("H"), date("i"), 0, date("m"), date("d"), date("Y"));
		$query = 'SELECT n FROM AcmeTaskBundle:Notification n WHERE n.datetime <= :now';
		
		try{
			return $this->getEntityManager()
				->createQuery($query)
				->setParameter('now', $now)
				->getResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    	}
	}
	public function findByThisMonth($user,$year,$month) {
		//get no repeat
		$thisMonth = mktime(0, 0, 0, $month, 1, $year);
		$nextMonth = mktime(0, 0, 0, ($month+1), 1, $year);
		$query = '
			SELECT n
			FROM AcmeTaskBundle:Notification n, AcmeTaskBundle:Task t
				WHERE (n.datetime > :thisMonth AND n.datetime < :nextMonth)
					AND t.userId = :userId
					AND n.taskId = t.id';
		/*$query = 'SELECT t FROM AcmeTaskBundle:Notification n , AcmeTaskBundle:Task t
						WHERE 
							(n.datetime > :thisMonth AND n.datetime < :nextMonth)
							';*/
		$month = $this->getEntityManager()
			->createQuery($query)
			->setParameter('thisMonth', $thisMonth)
			->setParameter('nextMonth', $nextMonth)
			->setParameter('userId', $user->getId())
			->getResult();
		//
		return $month;
	}
}