<?php

namespace Acme\ScheduleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends EntityRepository
{
	public function findAllTasks() {
		$schedule = $this->getEntityManager()
            ->createQuery('SELECT s FROM AcmeScheduleBundle:Schedule s ORDER BY s.id ')
            ->getResult();
      return $schedule;
	}
	public function findOneByCommandAndArgument($command,$arg) {
		
		try{
			return $this->getEntityManager()
            		->createQuery('SELECT s FROM AcmeScheduleBundle:Schedule s 
            		WHERE s.command = :command AND s.arguments = :arg ')
            		->setParameter('command', $command)
						->setParameter('arg', $arg)
						->setMaxResults(1)
            		->getSingleResult();
      } catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    	}
	}
}