<?php

namespace Acme\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	function getThisDate($string) {
		$string = mysql_real_escape_string($string);
		if(strlen($string)>64)return -3;
		if(is_numeric($string)) {//num of days
			return date("Y:m:d H:i:s",strtotime(date("Y:m:d H:i:s") . " +$string days"));
		}
		else {
			$string = strtolower($string);
			if(preg_match('/last/',$string))return "i think ppl put todo notes for past :P";	
			$days_of_week = array('/next monday/'=>'next monday','/next tuesday/'=>'next tuesday','/next wednesday/'=>'next wednesday','/next thursday/'=>'next thursday','/next friday/'=>'next friday','/next saturday/'=>'next saturday','/next sunday/'=>'next sunday','/next month/'=>'next month','/next year/'=>'next year'
			,'/coming monday/'=>'next monday','/coming tuesday/'=>'next tuesday','/coming wednesday/'=>'next wednesday','/coming thursday/'=>'next thursday','/coming friday/'=>'next friday','/coming saturday/'=>'next saturday','/coming sunday/'=>'next sunday','/coming month/'=>'next month','/coming year/'=>'next year'
			,'/monday/'=>'monday','/tuesday/'=>'monday','/wednesday/'=>'monday','/thursday/'=>'monday','/friday/'=>'monday','/saturday/'=>'monday','/sunday/'=>'monday','/month/'=>'monday','/year/'=>'monday','/weekend/'=>'saturday','/week end/'=>'saturday'
			);
			foreach($days_of_week as $day => $value){
				if(preg_match($day, $string)){
				return date("Y:m:d H:i:s",strtotime($value));}
			}
			$days_of_week = array('/tomoro/'=>'1','/day after tomoro/'=>'2');
			foreach($days_of_week as $day => $value){
				if(preg_match($day, $string))
				return date("Y:m:d H:i:s",strtotime(date("Y:m:d H:i:s") . " +$value days"));
			}
			return "couldnt find the date";
		}
	}
	public function findByThisMonth() {
		$thisMonth = mktime(0, 0, 0, date('m'), 1, date('Y'));
		$nextMonth = mktime(0, 0, 0, (date('m')+1), 1, date('Y'));
		$query = 'SELECT t FROM AcmeTaskBundle:Task t WHERE t.datetime > :thisMonth AND t.datetime < :nextMonth';
		
		return $this->getEntityManager()
			->createQuery($query)
			->setParameter('thisMonth', $thisMonth)
			->setParameter('nextMonth', $nextMonth)
			->getResult();
	}
}