parameters:
#    acme_location.example.class: Acme\LocationBundle\Example

services:
#    acme_location.example:
#        class: %acme_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
