<?php

namespace Acme\LearningBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LearnUserLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LearnUserLocationRepository extends EntityRepository
{
	public function findByOwnerId($userId) {
		
		$query = 'SELECT l FROM AcmeLearningBundle:SampleLocation l WHERE l.title NOT IN (SELECT ul.title FROM AcmeLearningBundle:LearnUserLocation ul WHERE ul.userId = :userId)';
		$locations = $this->getEntityManager()
            		->createQuery($query)
            		->setParameter('userId', $userId)
            		->getResult();
    	return $locations;
	}
}