Acme\TaskBundle\Entity\TaskColour:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    code:
      type: string
      length: '11'
    colour:
      type: string
      length: '25'
  lifecycleCallbacks: {  }
  oneToMany:
       task:
            targetEntity: Task
            mappedBy: taskColour