Acme\TaskBundle\Entity\Task:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    calendarId:
      type: integer
      length: '11'
    task:
      type: string
      length: '255'
    description:
      type: text
      length: null
    dueDate:
      type: integer
      length: '11'
  lifecycleCallbacks: {  }
