Acme\TaskBundle\Entity\Task:
  type: entity
  repositoryClass: Acme\TaskBundle\Entity\TaskRepository
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    calendarId:
      type: integer
      length: '11'
      nullable: true
      default: 0      
    task:
      type: string
      length: '255'
    description:
      type: text
      length: null
    datetime:
      type: integer
      length: '11'
    location:
      type: string
      lenth: '255'
    lng:
      type: float
    lat:
      type: float
  lifecycleCallbacks: {  }
