AcmeScheduleBundle:
    resource: "@AcmeScheduleBundle/Resources/config/routing.yml"
    prefix:   /

AcmeMobileBundle:
    resource: "@AcmeMobileBundle/Resources/config/routing.yml"
    prefix:   /mobile

AcmeDashBundle:
    resource: "@AcmeDashBundle/Resources/config/routing.yml"
    prefix:   /dash

AcmeEventsBundle:
    resource: "@AcmeEventsBundle/Resources/config/routing.yml"
    prefix:   /

AcmeNewsBundle:
    resource: "@AcmeNewsBundle/Resources/config/routing.yml"
    prefix:   /

AcmeWeatherBundle:
    resource: "@AcmeWeatherBundle/Resources/config/routing.yml"
    prefix:   /

AcmeLocationBundle:
    resource: "@AcmeLocationBundle/Resources/config/routing.yml"
    prefix:   /

AcmeCalendarBundle:
    resource: "@AcmeCalendarBundle/Resources/config/routing.yml"
    prefix:   /

AcmeMemberBundle:
    resource: "@AcmeMemberBundle/Resources/config/routing.yml"
    prefix:   /

AcmeMenusBundle:
    resource: "@AcmeMenusBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

###############
#   my ones   #
###############
AcmeHomeBundle:
    resource: "@AcmeHomeBundle/Resources/config/routing.yml"
    prefix:   /

AcmeUserBundle:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

AcmeProfileBundle:
    resource: "@AcmeProfileBundle/Resources/config/routing.yml"
    prefix:   /

AcmeStoreBundle:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

AcmeTaskBundle:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix:   /task

AcmeNotificationsBundle:
    resource: "@AcmeNotificationsBundle/Resources/config/routing.yml"
    prefix:   /notification

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
