<?php

namespace Acme\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function findOneByDatetimeAndLocation($location)
	{
		$yesterday = strtotime('yesterday');
		$today = strtotime('today');
		$query = 'SELECT n FROM AcmeNewsBundle:News n 
						WHERE n.datetime > :yesterday 
							AND n.datetime < :today 
							AND n.location = :location 
						ORDER BY n.datetime ASC';
		return $this->getEntityManager()
			->createQuery($query)
			->setParameter('yesterday', $yesterday)
			->setParameter('today', $today)
			->setParameter('location', $location)
			->setMaxResults(25)
			->getResult();
	}
}