parameters:
#    acme_weather.example.class: Acme\WeatherBundle\Example

services:
#    acme_weather.example:
#        class: %acme_weather.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
