Acme\CalendarBundle\Entity\Calendar:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    title:
      type: string
      length: '255'
    enabled:
      type: boolean
    description:
      type: text
      length: null
    ownerId:
      type: integer
      length: '11'
    privacyType:
      type: string
      length: '7'
  lifecycleCallbacks: {  }
