Acme\WeatherBundle\Entity\WCondition:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: '50'
    icon:
      type: string
      length: '255'
    criticality:
      type: float
      length: 2
  lifecycleCallbacks: {  }
  oneToMany:
        weather:
            targetEntity: Weather
            mappedBy: condition
        wcondition:
            targetEntity: Acme\TaskBundle\Entity\Notification
            mappedBy: wcondition
