parameters:
#    acme_events.example.class: Acme\EventsBundle\Example

services:
#    acme_events.example:
#        class: %acme_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
