<?php

namespace Acme\CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends EntityRepository
{
	public function findOneByCalendarName($name,$user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM AcmeCalendarBundle:Calendar c WHERE c.title = \''.$name.'\' AND c.ownerId	= '.$user->getId().' ')
            ->getResult();
    }
}