AcmeNotificationsBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeNotificationsBundle:Default:index }

AcmeNotificationsBundle_edit_id:
    pattern:  /edit/{id}
    defaults: { _controller: AcmeNotificationsBundle:Dash:edit }
    requirements:
        id:  \d+

AcmeNotificationsBundle_confirm_push:
    pattern:  /push/comfirm
    defaults: { _controller: AcmeNotificationsBundle:Default:confirmPush }
    
AcmeNotificationsBundle_call_details:
    pattern:  /call/voice/{id}/{confirmId}
    defaults: { _controller: AcmeNotificationsBundle:Default:callDetails }
    requirements:
        id:  \d+