parameters:
#    acme_notifications.example.class: Acme\NotificationsBundle\Example

services:
#    acme_notifications.example:
#        class: %acme_notifications.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
