<?php

namespace Acme\WeatherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* WeatherRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class WeatherRepository extends EntityRepository
{
	public function findOneByDatetimeAndLocation($day,$location)
	{
		
		$datetime = mktime($hour = null, $minute = null, $second = null, date("n",$day),  date("j",$day), date("Y",$day));
		$query = 'SELECT w FROM AcmeWeatherBundle:Weather w WHERE w.datetime = :date AND w.location = :location';
		try{
		$w = $this->getEntityManager()
			->createQuery($query)
			->setParameter('date', $datetime)
			->setParameter('location', $location)
			->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
        return null;
    	}
			//add vals from condition
		$w->icon = $w->getWcondition()->getIcon();
		$w->condition = $w->getWcondition()->getName();
		return $w;
		
	}
}