AcmeNewsBundl_test:
    pattern:  /news/test
    defaults: { _controller: AcmeNewsBundle:Default:index }

AcmeNewsBundle_ajax_panel:
    pattern:  /news/ajax/panel
    defaults: { _controller: AcmeNewsBundle:Default:ajax }
