parameters:
#    acme_news.example.class: Acme\NewsBundle\Example

services:
#    acme_news.example:
#        class: %acme_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
