parameters:
#    acme_schedule.example.class: Acme\ScheduleBundle\Example

services:
#    acme_schedule.example:
#        class: %acme_schedule.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
