AcmeTaskBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTaskBundle:Default:index }

AcmeTaskBundle_success:
    pattern:  /task/success
    defaults: { _controller: AcmeTaskBundle:Default:index }

AcmeTaskBundle_addnewtask:
    pattern:  /task/new
    defaults: { _controller: AcmeTaskBundle:Panel:addNewTask }
    
AcmeTaskBundle_edit_id:
    pattern:  /task/edit/{id}
    defaults: { _controller: AcmeTaskBundle:Day:edit }
    requirements:
        id:  \d+
        
AcmeTaskBundle_delete:
    pattern:  /task/delete
    defaults: { _controller: AcmeTaskBundle:Default:delete }