AcmeTaskBundle_success:
    pattern:  /success
    defaults: { _controller: AcmeTaskBundle:Default:index }

AcmeTaskBundle_addnewtask:
    pattern:  /new
    defaults: { _controller: AcmeTaskBundle:Panel:addNewTask }
    
AcmeTaskBundle_edit_id:
    pattern:  /edit/{id}
    defaults: { _controller: AcmeTaskBundle:Dash:edit }
    requirements:
        id:  \d+
        
AcmeTaskBundle_delete:
    pattern:  /delete
    defaults: { _controller: AcmeTaskBundle:Default:delete }