AcmeTaskBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTaskBundle:Default:index }

AcmeTaskBundle_success:
    pattern:  /task/success
    defaults: { _controller: AcmeTaskBundle:Default:index }

AcmeTaskBundle_new:
    pattern:  /task/new
    defaults: { _controller: AcmeTaskBundle:Default:new }