parameters:
#    acme_task.example.class: Acme\TaskBundle\Example

services:
#    acme_task.example:
#        class: %acme_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
