parameters:
#    acme_menus.example.class: Acme\MenusBundle\Example

services:
#    acme_menus.example:
#        class: %acme_menus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
