AcmeUserBundle_profile_edit:
    pattern:  /member/profile/edit
    defaults: { _controller: AcmeUserBundle:Profile:edit }

AcmeUserBundle_profile:
    pattern:  /member/profile
    defaults: { _controller: AcmeUserBundle:Profile:profile }
    
AcmeUserBundle_login_fail:
    pattern:  /user/login_check
    defaults: { _controller: AcmeUserBundle:Default:loginFailure }