parameters:
#    acme_calendar.example.class: Acme\CalendarBundle\Example

services:
#    acme_calendar.example:
#        class: %acme_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
